### PR TITLE
Iniitialize status conditions

### LINKED ISSUE #177: No error reporting when service is not matched
### About

When creating a ServiceBinding resource with a `.spec.service` reference that cannot be resolved, the ServiceBinding resource does not set a failure condition and the controller does not include any useful error messages. This seems to happen if it cannot find the resource for any reason, e.g.  an incorrect apiVerison/Kind/or Name. This makes it hard to debug the problem.

Looking at the controller logs this is the only error that appears, perhaps it's failing while trying to update the status?

> {"severity":"ERROR","timestamp":"2021-09-16T16:38:57.735387879Z","logger":"webhook","caller":"controller/controller.go:548","message":"Reconcile error","knative.dev/controller":"github.com.vmware-labs.service-bindings.pkg.reconciler.servicebinding.Reconciler","knative.dev/kind":"servicebinding.io.ServiceBinding","duration":"12.506546ms","error":"ServiceBinding.servicebinding.io \"rmq-binding\" is invalid: [status.conditions.status: Unsupported value: \"\": supported values: \"True\", \"False\", \"Unknown\", status.conditions.lastTransitionTime: Invalid value: \"null\": status.conditions.lastTransitionTime in body must be of type string: \"null\", status.conditions.reason: Invalid value: \"\": status.conditions.reason in body should be at least 1 chars long]","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20210331065221-952fdd90dbb0/controller/controller.go:548\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20210331065221-952fdd90dbb0/controller/controller.go:531\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20210331065221-952fdd90dbb0/controller/controller.go:468"}

Using this release https://github.com/vmware-labs/service-bindings/releases/download/v0.5.0/service-bindings-0.5.0.yaml

### To reproduce
1. Install 0.5.0 `kapp deploy -a service-bindings -f https://github.com/vmware-labs/service-bindings/releases/download/v0.5.0/service-bindings-0.5.0.yaml`
1. Install the RMQ operator `kubectl apply -f https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml`
1. Apply the following YAML - note we have not created the referenced RMQ.
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-binding-rmq
  labels:
    servicebinding.io/controller: "true"
rules:
- apiGroups: ["rabbitmq.com"]
  resources: ["rabbitmqclusters"]
  verbs: ["get", "list", "watch"]

---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: rmq-binding
spec:
  service:
    apiVersion: rabbitmq.com/v1beta1
    kind: RabbitmqCluster
    name: hello-world
  workload:
    apiVersion: apps/v1
    kind: Deployment
    name: rmq-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq-app
  labels:
    app: rmq-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmq-app
  template:
    metadata:
      labels:
        app: rmq-app
    spec:
      containers:
      - name: spring-rabbitmq-app
        image: ismteam/spring-rabbitmq-app:latest
        imagePullPolicy: IfNotPresent
```
4. Check the binding resource - verify you get no status updated and no updated conditions.
```bash
k get servicebinding
NAME          READY   REASON   AGE
rmq-binding                    3m45s
```

### PR DESCRIPTION
**Pull request by shashwathi**
Pull request

### What this PR does / why we need it
K8s API server is rejecting status condition with no values. So update initialize conditions func to initialize all fields in status resource.

### Which issue(s) this PR fixes
Fixes #177 

### Describe testing done for PR
Use the testcase from #177 issue.

### CODE REVIEW

File: pkg/apis/servicebinding/v1alpha3/servicebinding_lifecycle.go [hunk 1]
```diff
@@ -19,12 +19,13 @@ const (
...
 	ServiceBindingConditionProjectionReady  = "ProjectionReady"
+	InitializeConditionReason               = "Unknown"
 )
 
-func (bs *ServiceBindingStatus) InitializeConditions() {
-	ready := metav1.Condition{Type: ServiceBindingConditionReady}
-	serviceAvailable := metav1.Condition{Type: ServiceBindingConditionServiceAvailable}
-	projectionReady := metav1.Condition{Type: ServiceBindingConditionProjectionReady}
+func (bs *ServiceBindingStatus) InitializeConditions(now metav1.Time) {
+	ready := metav1.Condition{Type: ServiceBindingConditionReady, Status: metav1.ConditionUnknown, LastTransitionTime: now, Reason: InitializeConditionReason}
```
Comment (rashedkvm) [inline pkg/apis/servicebinding/v1alpha3/servicebinding_lifecycle.go:26]: Wondering if it would be simpler to set the `metav1.time` inside the method. Perhaps the unit test will be challenging!

File: pkg/apis/servicebinding/v1alpha3/servicebinding_test.go [hunk 2]
```diff
@@ -442,7 +456,7 @@ func TestServiceBindingStatus_MarkServiceAvailable(t *testing.T) {
 			{
 				Type:               ServiceBindingConditionReady,
 				Status:             metav1.ConditionUnknown,
-				Reason:             "Unknown",
+				Reason:             "ProjectionReadyUnknown",
```
Comment (rashedkvm) [inline pkg/apis/servicebinding/v1alpha3/servicebinding_test.go:459]: Is that Reason `ProjectionReadyUnknown` correct? Can you please help me with some detail for this reason value?

File: pkg/apis/servicebinding/v1alpha3/servicebinding_test.go [hunk 3]
```diff
@@ -572,11 +587,21 @@ func TestServiceBindingStatus_aggregateReadyCondition(t *testing.T) {
 					{
 						Type:               ServiceBindingConditionReady,
 						Status:             "Unknown",
+						Reason:             "ServiceAvailableUnknown",
```
Comment (rashedkvm) [inline pkg/apis/servicebinding/v1alpha3/servicebinding_test.go:590]: `ServiceAvailableUnknown`  - same question here as well

File: pkg/apis/servicebinding/v1alpha3/servicebinding_lifecycle.go (hunk 1 above)
Comment (shashwathi) [reply pkg/apis/servicebinding/v1alpha3/servicebinding_lifecycle.go:26]: Yup you guessed it right

File: pkg/apis/servicebinding/v1alpha3/servicebinding_test.go (hunk 2 above)
Comment (shashwathi) [reply pkg/apis/servicebinding/v1alpha3/servicebinding_test.go:459]: aggregare func builds the reason string with sub condition type + condition reason. Same for other comment

**Review by suarezjulian — APPROVED** [review]
LGTM

**Comment by scothis** [comment]
Still seeing this behavior in v0.6.0
